# trigger schedule

name: ticket-checker2

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run script
        run: python ticket_checker.py

