name: ticket-checker

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run script
        run: python ticket_checker.py
